"""Role and permission constants."""

# System role names (used for RBAC)
ROLE_OWNER = "owner"
ROLE_ADMIN = "admin"
ROLE_FINANCE = "finance"
ROLE_SALES = "sales"
ROLE_WAREHOUSE = "warehouse"
ROLE_EMPLOYEE = "employee"

DEFAULT_ROLES = [
    ROLE_OWNER,
    ROLE_ADMIN,
    ROLE_FINANCE,
    ROLE_SALES,
    ROLE_WAREHOUSE,
    ROLE_EMPLOYEE,
]

# Permission codes (resource:action)
PERM_MANAGE_COMPANY = "company:manage"
PERM_MANAGE_USERS = "users:manage"
PERM_MANAGE_ROLES = "roles:manage"
PERM_VIEW_PRODUCTS = "products:view"
PERM_MANAGE_PRODUCTS = "products:manage"
PERM_VIEW_ORDERS = "orders:view"
PERM_MANAGE_ORDERS = "orders:manage"
PERM_VIEW_INVOICES = "invoices:view"
PERM_MANAGE_INVOICES = "invoices:manage"
PERM_VIEW_PAYMENTS = "payments:view"
PERM_MANAGE_PAYMENTS = "payments:manage"
PERM_VIEW_LEDGER = "ledger:view"
PERM_MANAGE_LEDGER = "ledger:manage"
PERM_VIEW_AUDIT = "audit:view"

DEFAULT_PERMISSIONS = [
    PERM_MANAGE_COMPANY,
    PERM_MANAGE_USERS,
    PERM_MANAGE_ROLES,
    PERM_VIEW_PRODUCTS,
    PERM_MANAGE_PRODUCTS,
    PERM_VIEW_ORDERS,
    PERM_MANAGE_ORDERS,
    PERM_VIEW_INVOICES,
    PERM_MANAGE_INVOICES,
    PERM_VIEW_PAYMENTS,
    PERM_MANAGE_PAYMENTS,
    PERM_VIEW_LEDGER,
    PERM_MANAGE_LEDGER,
    PERM_VIEW_AUDIT,
]

# Role -> permissions mapping (owner gets all)
ROLE_PERMISSIONS: dict[str, list[str]] = {
    ROLE_OWNER: DEFAULT_PERMISSIONS,
    ROLE_ADMIN: [
        PERM_MANAGE_USERS,
        PERM_MANAGE_ROLES,
        PERM_VIEW_PRODUCTS,
        PERM_MANAGE_PRODUCTS,
        PERM_VIEW_ORDERS,
        PERM_MANAGE_ORDERS,
        PERM_VIEW_INVOICES,
        PERM_MANAGE_INVOICES,
        PERM_VIEW_PAYMENTS,
        PERM_MANAGE_PAYMENTS,
        PERM_VIEW_LEDGER,
        PERM_MANAGE_LEDGER,
        PERM_VIEW_AUDIT,
    ],
    ROLE_FINANCE: [
        PERM_VIEW_PRODUCTS,
        PERM_VIEW_ORDERS,
        PERM_VIEW_INVOICES,
        PERM_MANAGE_INVOICES,
        PERM_VIEW_PAYMENTS,
        PERM_MANAGE_PAYMENTS,
        PERM_VIEW_LEDGER,
        PERM_MANAGE_LEDGER,
        PERM_VIEW_AUDIT,
    ],
    ROLE_SALES: [
        PERM_VIEW_PRODUCTS,
        PERM_MANAGE_PRODUCTS,
        PERM_VIEW_ORDERS,
        PERM_MANAGE_ORDERS,
        PERM_VIEW_INVOICES,
        PERM_VIEW_PAYMENTS,
        PERM_VIEW_LEDGER,
    ],
    ROLE_WAREHOUSE: [
        PERM_VIEW_PRODUCTS,
        PERM_MANAGE_PRODUCTS,
        PERM_VIEW_ORDERS,
        PERM_MANAGE_ORDERS,
        PERM_VIEW_LEDGER,
    ],
    ROLE_EMPLOYEE: [
        PERM_VIEW_PRODUCTS,
        PERM_VIEW_ORDERS,
        PERM_VIEW_INVOICES,
        PERM_VIEW_PAYMENTS,
        PERM_VIEW_LEDGER,
    ],
}
